pax2pay/model-banking

- Client/Operations.ts
> Adding range to Operations

- Client/Transactions/index.ts
Closes https://github.com/pax2pay/worker-banking-ledger/issues/326 - depends on https://github.com/pax2pay/worker-banking-ledger/pull/333
> Added transaction list options

- Client/Accounts.ts
- Client/Operations.ts
- Client/Organizations.ts
- Client/Transactions/index.ts
> pass headers in list functions

- Client/Settlements.ts
- package-lock.json
Goes with https://github.com/pax2pay/worker-banking-card/pull/64
> Updated settlement client.

- Rail/Type.ts
- Rail/index.ts
Put string literal rails type in Rail index.
Added isly stuff.
> Removed annoying and stupid Rail/Type file.

- Transaction/Creatable.spec.ts
- Transaction/Creatable.ts
The isly type for Transaction.Creatable was broken and this fixes it.
> Fix type for transaction creatable.

- Identifier.spec.ts
- Identifier.ts
- package-lock.json
- package.json
Created function for decoding ids and getting out the time used to generate it.
> Get time from id.

- Rail/index.ts
Moving it to ledger internal type.
> Removed "reference" on Rail type.

- Rail/index.spec.ts
- Rail/index.ts
> Rail compare function to see if two instances of Rail have the same values

- Rule/Rule.ts
- Transaction/Note.ts
This will allow better formatting in Note table
> Rule on Note to replace Rule.stringify

- Rule/State/Authorization.ts
- Rule/State/Card.ts
- Rule/State/Transaction.ts
- Rule/State/index.spec.ts
> Added back amount related fields on Authorization State.

- Rule/State/Account.ts
Relates to [#797](https://github.com/pax2pay/worker-banking-ledger/issues/797)
> Optional properties in rule account state

- Supplier/index.ts
- Treasury/Account/Conditions.ts
- Treasury/Account/Creatable.ts
- Treasury/Account/Storable.ts
- Treasury/Account/index.ts
- Treasury/index.ts
- package-lock.json
- package.json
Part of [#832](https://github.com/pax2pay/worker-banking-ledger/issues/832)
> Created a Conditions type on Treasury Account

- Client/Treasury.ts
- Key/Permissions.ts
Fixed rebalance endpoint path in client.
> Added key permissions.

- Transaction/index.spec.ts
- Transaction/index.ts
- package-lock.json
- package.json
https://github.com/pax2pay/worker-banking-ledger/issues/1220
> New headers and formatting of transaction csv

- Analytics/Configuration/index.ts
selectively filters are applied on event before mapping
> selectively filter correct properties

- Analytics/Configuration/AuditLog.ts
closes https://github.com/pax2pay/worker-banking-ledger/issues/1497
> Audit log backup model

- Settlement/index.ts
- Warning/Settlement/MissingFile.ts
- Warning/Settlement/NegativeAmount.ts
- Warning/Settlement/UnknownEntry.ts
- Warning/Settlement/index.ts
- Warning/index.ts
Closes https://github.com/pax2pay/worker-banking-ledger/issues/1534
> Settlement warnings

- Analytics/Configuration/Transaction.spec.ts
- Analytics/Configuration/Transaction.ts
- Rule/State/Transaction.ts
- Rule/State/index.ts
- Transaction/Incoming.spec.ts
- Transaction/index.spec.ts
- Transaction/index.ts
- index.spec.ts
- verifier/index.spec.ts
Closes https://github.com/pax2pay/worker-banking-ledger/issues/1566
> Detailed transaction amount

- Client/Transactions/index.ts
Closes https://github.com/pax2pay/worker-banking-ledger/issues/1641
> Transaction statistics client

- Client/Transactions/index.ts
- Transaction/Statistics.ts
...and rewrite synonymous array checks to use same function.
> Add limit to transaction statistics query

- Operation/index.spec.ts
- Transaction/index.ts
Removed some unnecessary lines.
> Optionalized operations on transactions.

- Client/Accounts/History.ts
- Client/Accounts/Rails.ts
- Client/Accounts/index.ts
- Client/Cards.ts
- Client/Exchanges.ts
- Client/Operations.ts
- Client/Organizations/Groups.ts
- Client/Organizations/index.ts
- Client/Reports.ts
- Client/Transactions/Notes.ts
- Client/Transactions/index.ts
- Client/Version.ts
- Client/index.ts
- package-lock.json
- package.json
> Removed cloudly rest.

- Client/index.ts
> Stop using organization undefined in client.

- Rule/Charge.ts
- Rule/Reserve.ts
> [fx fee] Added notes to remember what the authorized and captured charges were.
